--- 
bundler_args: "--without development acceptance"
cache: bundler
env: 
  - PUPPET_GEM_VERSION="3.8.4"
  - "PUPPET_GEM_VERSION=\"~> 4.0\" STRICT_VARIABLES=\"yes\""
language: ruby
matrix: 
  exclude: 
    - 
      env: "PUPPET_GEM_VERSION=\"~> 4.0\" STRICT_VARIABLES=\"yes\""
      rvm: "1.9.3"
  fast_finish: true
notifications: 
  email: false
  webhooks: 
    on_failure: always
    on_success: change
    urls: 
      - "https://webhooks.gitter.im/e/3477acef6dd93b015c9b"
rvm: 
  - "1.9.3"
  - "2.1.5"
  - "2.1.6"
script: 
  - "bundle exec rake lint"
  - "bundle exec rake validate"
  - "bundle exec rake spec SPEC_OPTS='--format documentation'"
sudo: false
